<link rel="stylesheet" href="<?= $base_url ?>assets/bootstrap/css/bootstrap.min.css"/>
<link rel="stylesheet" href="<?= $base_url ?>assets/icofont/icofont.min.css"/>
<link rel="stylesheet" href="<?= $base_url ?>CSSstyle/CSSview/navigasi-header.css"/>
<link rel="stylesheet" href="<?= $base_url ?>CSSstyle/CSSview/navigasi-category.css"/>
<link rel="stylesheet" href="<?= $base_url ?>CSSstyle/CSSview/navigasi-footer.css"/>
<link rel="stylesheet" href="<?= $base_url ?>CSSstyle/CSSview/product-card.css"/>
<link rel="stylesheet" href="<?= $base_url ?>CSSstyle/CSSview/carousel-slider.css"/>
<link rel="stylesheet" href="<?= $base_url ?>CSSstyle/product-page.css"/>
<link rel="stylesheet" href="<?= $base_url ?>CSSstyle/cart-page.css"/>
<link rel="stylesheet" href="<?= $base_url ?>CSSstyle/mainstyle.css"/>